chore: manual release sdist
Signed-off-by: Aaron <29749331+aarnphm@users.noreply.github.com>

diff --git a/tools/release b/tools/release
--- a/tools/release
+++ b/tools/release
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-set -exu
+set -e
 
 if [ "$#" -eq 1 ]; then
     VERSION=$1
@@ -21,6 +21,14 @@ fi
 GIT_ROOT=$(git rev-parse --show-toplevel)
 cd "$GIT_ROOT" || exit 1
 
+# This script should only be run by me :smile:
+if [ ! -f "$HOME"/.pypirc ]; then
+    # about .pypirc file:
+    # https://docs.python.org/3/distutils/packageindex.html#the-pypirc-file
+    echo "Error: File \$HOME/.pypirc not found."
+    exit 1
+fi
+
 if [ -d "$GIT_ROOT"/dist ]; then
     echo "Removing existing 'dist' and 'build' directory to get a clean build"
     rm -rf "$GIT_ROOT"/dist
@@ -28,6 +36,10 @@ if [ -d "$GIT_ROOT"/dist ]; then
 fi
 
 tag_name="v$VERSION"
+
+echo "Install dependencies"
+
+pip install twine wheel build
 
 if git rev-parse "$tag_name" > /dev/null 2>&1; then
     echo "git tag '$tag_name' exist, using existing tag."
@@ -46,3 +58,17 @@ else
 
     git push origin "$tag_name"
 fi
+
+echo "Generating PyPI source distribution..."
+cd "$GIT_ROOT" || exit 1
+
+python -m build -s
+
+# Use testpypi by default, run script with: "REPO=pypi release.sh" for
+# releasing to Pypi.org
+REPO=${REPO:=testpypi}
+
+echo "Uploading sdist to $REPO..."
+twine upload --repository "$REPO" dist/* --verbose
+
+echo "Done releasing version $VERSION."
